
sm_build: 
	+make -C pb sm_build
	+make -C smn_itf sm_build

sm_build_all: 
	+make -C pb sm_build_all
	+make -C smn_itf sm_build_all

sm_clean_o:
	rm -rf ./*.o ./run.main
	+make -C pb sm_clean_o
	+make -C smn_itf sm_clean_o

