
sm_build: 
	+make -C ano_rpc_itf sm_build
	+make -C rpc_itf sm_build

sm_build_all: 
	+make -C ano_rpc_itf sm_build_all
	+make -C rpc_itf sm_build_all

sm_clean_o:
	rm -rf ./*.o
	+make -C ano_rpc_itf sm_clean_o
	+make -C rpc_itf sm_clean_o

